version: "3"
services:
  backend:
    build: ./
    ports:
      - "5555:5555"
    depends_on:
      - db
    container_name: alteos-contacts-app-backend
    environment:
      - MONGODB_URI=mongodb://db:27017/alteos-contacts-app
  client:
    build: ./client
    ports:
      - "3000:3000"
    container_name: alteos-contacts-app-client
  db:
    image: mongo
    ports:
      - "27017:27017"
